[package]
name = "code-minimap"
version = "0.1.0"
authors = ["Wenxuan Zhang <wenxuangm@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
exclude = [
    "/completions"
]

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.18"

[dependencies]
itertools = "0.9"
structopt = { version = "0.3", features = ["wrap_help"] }

[build-dependencies]
structopt = "0.3"

[profile.release]
lto = true
codegen-units = 1
